spring.datasource.url= jdbc:postgresql://localhost:5432/kycdata
spring.datasource.username= postgres
spring.datasource.password= Database@123
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update

app.jwt.secretKey=cp
